In [1]:
!pip install --upgrade google-cloud-bigquery pandas

Requirement already satisfied: google-cloud-bigquery in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (3.35.1)
Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.25.1)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-cloud-bigquery) (2.40.3)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-cloud-bigquery) (2.4.3)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-cloud-bigquery) (2.7.2)
Requirement already satisfied: packaging>=24.2.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery) (25.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (6.31.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.26.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.74.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.74.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.7.1)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2025.7.9)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install db-dtypes

Requirement already satisfied: db-dtypes in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (1.4.3)
Requirement already satisfied: numpy>=1.24.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from db-dtypes) (2.3.1)
Requirement already satisfied: packaging>=24.2.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from db-dtypes) (25.0)
Requirement already satisfied: pandas>=1.5.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from db-dtypes) (2.3.1)
Requirement already satisfied: pyarrow>=13.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from db-dtypes) (21.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from pandas>=1.5.3->db-dtypes) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.5.3->db-dtypes) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.5.3->db-dtypes) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->db-dtypes) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
from google.cloud import bigquery

project_id = "amex-analytics-project"
dataset_id = "amex_data"
table_id = "amex_complaints"

client = bigquery.Client(project=project_id)

In [4]:
query = f"""
SELECT * 
FROM `{project_id}.{dataset_id}.{table_id}`
LIMIT 10
"""
df = client.query(query).to_dataframe()
df.head()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,date_received,product,subproduct,issue,subissue,consumer_complaint_narrative,company,state,zip_code,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed,complaint_id,clean_text,vader_sentiment,sentiment_label
0,2015-03-19,credit card,,Rewards,,I have a American Express card where they are ...,american express company,CO,803XX,Not Provided,Consent provided,Web,2015-03-19,Closed with explanation,True,No,1291952,i have a american express card where they are ...,0.8553,positive
1,2015-03-20,credit card,,Rewards,,American Express has misguided me into closing...,american express company,NJ,070XX,Not Provided,Consent provided,Web,2015-03-20,Closed with non-monetary relief,True,No,1292634,american express has misguided me into closing...,0.7469,positive
2,2015-03-20,credit card,,Rewards,,This complaint is regarding the poor reward sy...,american express company,CO,94124,Not Provided,Consent provided,Web,2015-03-23,Closed with explanation,True,No,1293416,this complaint is regarding the poor reward sy...,0.9658,positive
3,2015-03-22,credit card,,Rewards,,I have XXXX amex credit card. I have accumulat...,american express company,KY,405XX,Not Provided,Consent provided,Web,2015-03-22,Closed with explanation,True,No,1294904,i have xxxx amex credit card i have accumulate...,0.8717,positive
4,2015-03-23,credit card,,Late fee,,1 ) XXXX automatically billed my American Expr...,american express company,ME,048XX,Older American,Consent provided,Web,2015-03-23,Closed with monetary relief,True,No,1296046,xxxx automatically billed my american express ...,0.9370,positive

In [5]:
query = f"""
SELECT COUNT(*) as total_complaints
FROM `{project_id}.{dataset_id}.{table_id}`
"""
client.query(query).to_dataframe()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

   total_complaints
0              5409

In [6]:
query = f"""
SELECT issue, COUNT(*) as complaint_count
FROM `{project_id}.{dataset_id}.{table_id}`
GROUP BY issue
ORDER BY complaint_count DESC
LIMIT 10
"""
client.query(query).to_dataframe()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

                                               issue  complaint_count
0    Problem with a purchase shown on your statement              922
1                 Other features, terms, or problems              598
2                              Getting a credit card              573
3                                   Fees or interest              470
4  Advertising and marketing, including promotion...              420
5                                            Rewards              291
6                               Closing your account              283
7                            Trouble using your card              248
8                                   Billing disputes              204
9                       Problem when making payments              157

In [7]:
query = f"""
SELECT submitted_via, COUNT(*) as count
FROM `{project_id}.{dataset_id}.{table_id}`
GROUP BY submitted_via
ORDER BY count DESC
"""
client.query(query).to_dataframe()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  submitted_via  count
0           Web   5409

In [8]:
query = f"""
SELECT FORMAT_DATE('%Y-%m', date_received) as month,
       COUNT(*) as total_complaints
FROM `{project_id}.{dataset_id}.{table_id}`
GROUP BY month
ORDER BY month
"""
client.query(query).to_dataframe()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

      month  total_complaints
0   2015-03                15
1   2015-04                42
2   2015-05                44
3   2015-06                38
4   2015-07                58
5   2015-08                49
6   2015-09                55
7   2015-10                34
8   2015-11                65
9   2015-12                48
10  2016-01                50
11  2016-02                51
12  2016-03                53
13  2016-04                50
14  2016-05                65
15  2016-06                68
16  2016-07                67
17  2016-08               119
18  2016-09               113
19  2016-10                69
20  2016-11                55
21  2016-12                70
22  2017-01                64
23  2017-02                67
24  2017-03                76
25  2017-04                44
26  2023-08                35
27  2023-09               154
28  2023-10               164
29  2023-11               169
30  2023-12               166
31  2024-01               207
32  2024-02               187
33  2024-03               197
34  2024-04               200
35  2024-05               176
36  2024-06               155
37  2024-07               168
38  2024-08               170
39  2024-09               153
40  2024-10               164
41  2024-11               154
42  2024-12               177
43  2025-01               247
44  2025-02               174
45  2025-03               180
46  2025-04               200
47  2025-05               254
48  2025-06                29

In [9]:
query = f"""
SELECT sentiment_label, COUNT(*) as count
FROM `{project_id}.{dataset_id}.{table_id}`
GROUP BY sentiment_label
ORDER BY count DESC
"""
client.query(query).to_dataframe()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  sentiment_label  count
0        positive   2834
1        negative   2062
2         neutral    513

In [10]:
query = f"""
WITH top_issues AS (
    SELECT issue
    FROM `{project_id}.{dataset_id}.{table_id}`
    GROUP BY issue
    ORDER BY COUNT(*) DESC
    LIMIT 5
)
SELECT issue, sentiment_label, COUNT(*) as count
FROM `{project_id}.{dataset_id}.{table_id}`
WHERE issue IN (SELECT issue FROM top_issues)
GROUP BY issue, sentiment_label
ORDER BY issue, count DESC
"""
client.query(query).to_dataframe()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

                                                issue sentiment_label  count
0   Advertising and marketing, including promotion...        positive    317
1   Advertising and marketing, including promotion...        negative     72
2   Advertising and marketing, including promotion...         neutral     31
3                                    Fees or interest        positive    254
4                                    Fees or interest        negative    172
5                                    Fees or interest         neutral     44
6                               Getting a credit card        positive    385
7                               Getting a credit card        negative    116
8                               Getting a credit card         neutral     72
9                  Other features, terms, or problems        positive    357
10                 Other features, terms, or problems        negative    202
11                 Other features, terms, or problems         neutral     39
12    Problem with a purchase shown on your statement        negative    634
13    Problem with a purchase shown on your statement        positive    196
14    Problem with a purchase shown on your statement         neutral     92

In [11]:
query = f"""
SELECT sentiment_label, timely_response, COUNT(*) as count
FROM `{project_id}.{dataset_id}.{table_id}`
GROUP BY sentiment_label, timely_response
ORDER BY sentiment_label, count DESC
"""
df = client.query(query).to_dataframe()
df.head()

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\cloud\bigquery\table.py:1965: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  sentiment_label  timely_response  count
0        negative             True   2062
1         neutral             True    513
2        positive             True   2834